### PR TITLE
Support GROUP and ORDER sobjects in FROM clause

### LINKED ISSUE #3: Add support for "Group" and "Order" as objects for FROM clause
The reserved list of keywords defined in the [isReserved](https://github.com/stomita/soql-parse/blob/master/dist/soql-parse.js#L5969) function check for `GROUP` and `ORDER` words as shown below:

```javascript
function isReserved(word) {
  return /^(SELECT|FROM|AS|USING|WHERE|AND|OR|NOT|GROUP|BY|ORDER|LIMIT|OFFSET|FOR|TRUE|FALSE|NULL)$/i.test(word);
}
```

However, the words [Group](https://developer.salesforce.com/docs/atlas.en-us.api.meta/api/sforce_api_objects_group.htm) and [Order](https://developer.salesforce.com/docs/atlas.en-us.api.meta/api/sforce_api_objects_order.htm) are queryable standard objects in Salesforce.

This issue is to request that the `isReserved(word)` function be modified so that it looks more specifically for `GROUP BY` and `ORDER BY` as reserved words.

For example, the following query is valid SOQL but fails to parse because the word `Group` in the FROM clause is flagged as a reserved word.
```
SELECT Name FROM Group WHERE Type = 'Queue' ORDER BY CreatedDate ASC
```

### LINKED ISSUE #5: Allow whitespace around date literals in WHERE clause
Example query that fails, note the whitespace between `LAST_N_DAYS` and `:` and `30` in the following code snippet:

```
SELECT Id, Name, CreatedDate
FROM Account
WHERE CreatedDate >= LAST_N_DAYS : 30
```

Same query as above, but without the whitespace around the date literal, which does successfully parse:

```
SELECT Id, Name, CreatedDate
FROM Account
WHERE CreatedDate >= LAST_N_DAYS:30
```

This request is to update the grammar to allow the extra whitespace as per the first example.

This was brought to my attention per https://github.com/douglascayers-org/sfdx-mass-action-scheduler/issues/67#issuecomment-502826342

Thanks

### PR DESCRIPTION
**Pull request by douglascayers**
* Fixes #3 
    * Adds `ObjectIdentifier` to grammar, used by `FromClause`
    * Adds new tests
        - 07-from-object-group-03.soql
        - 08-from-object-order-04.soql
* Fixes #5 
    * Adds support for whitespace around date literals
    * Adds new test
        - 41-date-literal-04.soql

### CODE REVIEW

**Comment by douglascayers** [comment]
👋 Hi @stomita, thanks for your awesome tools for Salesforce development.

When you get a chance I'd appreciate your review of this pull request that supports queries on the `Group` and `Order` standard objects.

Selfishly, this will also unblock some users of my open source app per https://github.com/douglascayers-org/sfdx-mass-action-scheduler/issues/89

Thank you!

**Comment by douglascayers** [comment]
Hi @paustint, I know you have an interest in this soql parsing library so I wanted to let you know about this new PR. If you have time to review and provide any feedback, I'd appreciate that too. Thanks!

**Review by stomita — APPROVED** [review]

**Comment by paustint** [comment]
@douglascayers - thanks, I will take a look when I get some time. There was not much activity in this repository and I had an immediate need, so I ended up creating my own parser library. You can check it out and see if it might be useful for you - https://github.com/paustint/soql-parser-js

**Comment by douglascayers** [comment]
Thanks for merging this request, @stomita

Thanks for the follow up, @paustint

**Pull request merged**
